db:
  env_file: '.docker-env'
  image: postgres:9.5
  ports:
    - "5431:5432"
web:
  build: .
  env_file: '.docker-env'
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db:db
